[tool.poetry]
name = "mokaoc-rag-chatbot"
version = "0.1.0"
description = "Chatbit pour MOKACO"
authors = ["Alex Kinda"]
readme = "README.md"

[tool.poetry.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"